# Generated by Django 3.2.9 on 2022-03-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='images',
            new_name='image',
        ),
    ]
