# Generated by Django 3.2.9 on 2022-03-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_rename_images_properties_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='image',
        ),
        migrations.AddField(
            model_name='properties',
            name='size',
            field=models.IntegerField(default=1500),
            preserve_default=False,
        ),
    ]
