# Generated by Django 3.2.9 on 2022-03-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20220312_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='properties',
            name='size',
            field=models.IntegerField(),
        ),
    ]
