# Generated by Django 3.2.9 on 2022-03-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_alter_properties_bedrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
