# Generated by Django 3.2.9 on 2022-03-12 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_properties_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='price',
        ),
    ]
