# Generated by Django 3.2.9 on 2022-03-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_remove_properties_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='price',
            field=models.IntegerField(default=100000),
            preserve_default=False,
        ),
    ]
