# Generated by Django 3.2.9 on 2022-03-12 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_properties_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='bedrooms',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='properties',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='properties',
            name='size',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100)]),
        ),
    ]
