# Generated by Django 3.2.9 on 2022-03-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_auto_20220312_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='image_compressed',
            field=models.ImageField(blank=True, upload_to='property_pics_compressed'),
        ),
    ]
