# Generated by Django 3.2.9 on 2022-03-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_properties_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='property_pics'),
        ),
    ]
