# Generated by Django 3.2.9 on 2022-03-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_properties_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='thumbnail',
            field=models.TextField(blank=True),
        ),
    ]
